services:
  app:
    image: todo-front-dev
    build:
      context: .
      dockerfile: dev.Dockerfile
    container_name: todo-front-dev
    ports:
      - 5173:5173
    volumes:
      - ./:/usr/src/app
