services:
  mongo-dev:
    image: mongo
    ports:
      - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongo_data_dev:/data/db
  redis-dev:
    image: redis
    ports:
      - 7891:6379
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ./todo-backend/redis_data_dev:/data
  backend-dev:
    image: todo-backend-dev
    container_name: todo-backend-dev
    build:
      context: ./todo-backend
      dockerfile: dev.Dockerfile
    # ports:
    #   - 3000:3000
    volumes:
      - ./todo-backend/:/usr/src/app
    environment:
      - MONGO_URL=mongodb://the_username:the_password@mongo-dev:27017/the_database
      - REDIS_URL=redis://redis-dev:6379
    depends-on:
      - redis-dev
      - mongo-dev

  frontend-dev:
    image: todo-front-dev
    container_name: todo-front-dev
    build:
      context: ./todo-frontend
      dockerfile: dev.Dockerfile
    volumes:
      - ./todo-frontend/:/usr/src/app
    # ports:
    #   - 5173:5173
    environment:
      - VITE_BACKEND_URL=http://localhost:8080/api
  reverse-proxy-dev:
    image: nginx:1.20.1
    container_name: reverse-proxy-dev
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      # only exposed port that can be reached from outside of container
      - 8080:80
    depends_on:
      - frontend-dev
      - backend-dev

volumes:
  mongo_data_dev:
